---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    regex: '[^A-Za-z0-9._-]'
    replace: '_'

  vars_files:
    - vars/default.yml

  roles:
    - docker

  tasks:
  - name: Ensure Nvidia GPU role if enabled
    ansible.builtin.import_role:
      name: gpu
    when: enable_nvidia_gpu is defined and enable_nvidia_gpu

  - name: Ensure template files
    template:
      src: '{{item.src}}'
      dest: '{{item.dest}}'
      mode: '{{item.mode}}'
      owner: '{{ansible_user}}'
      group: '{{ansible_user}}'
    loop:
      - { src: aws/credentials, dest: '/etc/passwd-s3fs', mode: '0600' }

  - name: Mount External Network volumes
    when: 
      - mounts is defined
    include_tasks: tasks/mount_network_volumes.yml

  - name: Ensure HMS-Docker role
    ansible.builtin.import_role:
      name: hmsdocker

  - name: Verify all Traefik endpoints are accessible
    ansible.builtin.uri:
      url: http://{{ item.key }}.{{ hms_docker_domain }}
      status_code: 200,302,401,403
      validate_certs: no
    with_dict:
      - "{{ hms_docker_container_map }}"
    when:
      - item.value.traefik is defined and item.value.traefik
      - item.value.enabled is defined and item.value.enabled
      - container_enabled_traefik
      - traefik_verify_endpoints is defined and traefik_verify_endpoints
