---
- name: Ensure Traefik config.
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ hms_docker_apps_path }}/traefik/config/traefik.yml"
    mode: 0644
    group: docker
    backup: yes
  notify: restart traefik

- name: Ensure Traefik certs directory
  ansible.builtin.file:
    path: "{{ hms_docker_apps_path }}/traefik/config/certs"
    state: directory
  register: traefik_certs_dir

- name: Ensure Traefik static file configs requirements
  block:
    - name: Ensure Traefik Static file dir
      ansible.builtin.file:
        path: "{{ traefik_ext_hosts_configs_path }}"
        state: directory
        mode: 0755
        group: docker
      register: traefik_additional_routes_dir

    - name: Ensure Traefik static file configs
      ansible.builtin.template:
        src: traefik_additional_routes.yml.j2
        dest: "{{ traefik_additional_routes_dir.path }}/{{ item.friendly_name | map('regex_replace', regex, replace) | list | join }}.yml"
        mode: 0644
        group: docker
        backup: yes
      with_items: "{{ traefik_ext_hosts_list }}"
      when: 
        - item.friendly_name is defined and item.friendly_name != ''
        - item.subdomain_name is defined and item.subdomain_name != ''
        - item.backend_url is defined and item.backend_url != ''
        - item.enabled is defined and item.enabled
  when: traefik_ext_hosts_enabled

#- name: Ensure disabled Traefik static file configs are removed
#  ansible.builtin.file:
#    path: "{{ traefik_additional_routes_dir.path }}/{{ item.friendly_name | map('regex_replace', regex, replace) | list | join }}.yml"
#    state: absent
#  with_items: "{{ traefik_ext_hosts_list }}"
#  when: 
#    - not item.enabled or not traefik_ext_hosts_enabled
